export const PERMISSIONS = {
  OVERVIEW_READ: 'overview.read',
  STAFF_MANAGE: 'staff.manage',
  ROLES_MANAGE: 'roles.manage',
  COST_VIEW: 'cost.view',
  PRICE_EDIT: 'price.edit',
  QUOTES_READ: 'quotes.read',
  QUOTES_WRITE: 'quotes.write',
  QUOTES_SEND: 'quotes.send',
  ORDERS_READ: 'orders.read',
  ORDERS_CREATE: 'orders.create',
  ORDERS_CONFIRM: 'orders.confirm',
  ADMIN_ALERTS_READ: 'admin.alerts.read',
  ADMIN_ALERTS_ACKNOWLEDGE: 'admin.alerts.acknowledge',
  INVENTORY_ADJUST: 'inventory.adjust',
  PAYMENTS_MANAGE: 'payments.manage',
  RECEIVABLES_VIEW: 'receivables.view',
  CUSTOMERS_READ: 'customers.read',
  CUSTOMERS_WRITE: 'customers.write',
  CUSTOMERS_EXPORT: 'customers.export',
  TASKS_MANAGE: 'tasks.manage',
  OPPORTUNITIES_MANAGE: 'opportunities.manage',
  CATALOG_READ: 'catalog.read',
  CATALOG_WRITE: 'catalog.write',
  MEDIA_MANAGE: 'media.manage',
  PURCHASING_READ: 'purchasing.read',
  PURCHASING_WRITE: 'purchasing.write',
  INVENTORY_READ: 'inventory.read',
  INVENTORY_RECEIVE: 'inventory.receive',
  CONNECTORS_MANAGE: 'connectors.manage',
} as const;

export const ALL_PERMISSION_KEYS = Object.values(PERMISSIONS);
